branches:
  only:
    - master

language: node_js

node_js:
  - stable

env:
  - API_DIR=server/api

cache:
  directories:
    - $API_DIR/node_modules

before_script:
  - openssl aes-256-cbc -K $encrypted_80b785a14e2e_key -iv $encrypted_80b785a14e2e_iv -in before_install.sh.enc -out $API_DIR/scripts/before_install.sh -d
  - chmod +x $API_DIR/scripts/before_install.sh
  - $API_DIR/scripts/before_install.sh

script:
  - cd $API_DIR
  - npm install
  - npm test

after_success:
  - npm run coveralls
