branches:
  only:
    - master

language: node_js

node_js:
  - "stable"

env:
  - API_DIR=server/api

cache:
  directories:
    - $API_DIR/node_modules

script:
  - cd $API_DIR
  - npm install
  - npm test
