branches:
  only:
    - master

language: node_js

node_js:
  - stable

env:
  matrix:
    - API_DIR=server/api
  global:
    - secure: MoC/z7wcyYjb+oFWI61rXY2yYHuupIh3/MvCmJ1H97ggPfwmxK5Ehmx3vK3PIRCAOCwnz8l6xacWJUHuRX74zybMRfwvhWg7zdNcMjDJOsGQdEtr85PgJXcJ9t1MYWq+pdddSEWLc9IrSUeqpchpJJZVU/g2uKMnOZIC5aA1/dqM1+JDatqvV7vWHLym4eCEYt0DL73Hpv1pnTgyV4gKrbAp6ZBXqhgMlK3726oW8FX42vtgBuJy/bwpnDC5oKz34wA8FdxeerDj1P50qiMRFb4RTlh6N24jvechtyFWMX7mdSqExT0y7EEErgIKXSdnuTbzEtY7MM/0kBUtfrwfRcIsmiLu8uUvV3XUhwWykBjwBcy1mf/vVXUu8nWVLlpmJjmXP7l8jWEO8jLHKJCNU5upBS4/bwBvJa+gdU+n4dx+S0YG4T8RkCSECb04NARMkehkq2RaLr3Fyhk//ydKeUNG5pPrUAr9c+2C8NFVRc0bvukXYai1/wky60gdqTWCZLMVhu6CYS3OsbvMkacceMWCbpeM33wlsmj6AgQ+PlALAwzYrwdH09QGQKq7coma1xsKV92w4/44+bJ67vj6auVevUiKrzGZIPqixO+883VSzx6wTz2BiO3CAvkIIed5bxX3uM7IiNxMqB5CpDIgBioSK8c49Vlzmmwe0pxEaF8=
    - secure: aLMCPR+xQ1M8IcqrPYcM/CfkYdnNXb/A6xb2baHNx7X9IQCyZqBKf/qDjg0e3KdTdacFwR3WXqGaYpPuP2DXmxJUggFjzbGDUb9Tm3T99/SI5Oo6d9h4qIQIlVbCpWF4SIkToFjlnuhHVAulmoQX+iAhqh//vokHLoAfMRxET7oe+Xeex2gYPZzeArM/Kxsgz7r8w5WPiTWRhE0rQ3I8M59gUSI5wxobnVZ3Yg7nlr1sU/nT4Dfxk5L2jtOCuTf8CvGYRjVxm0dswMUzEGC/Ky5yH32bxjGq5HzU3Nc7qLvYMKRo0j1fDbnL74TE+BWHAFhU4NsHP6Q91qec25H58PyIaSva8nizLQX/Qb/Hi34WmO9XhnEIe9mlrycrA0OqP6bcR9zhxLcZFHwmkxPulAcGQeJ5TstAegKt/Que+nE6VtO3br31HNNmViHT6n8acsjqboRC1yEyW0ZSA1mg6mGzefC9aC6iys7VPltM6K00Np1U7O6KbRweYtjmuBekNXoC0XXajmqPKebNbYVo8rr4XGnqTjHvSXmDBudzeOCZtya0sUUyUR0mEiKGkfoIXlDfHVI5nO3TstOlqfs1XlQS818RVzknn9wE1UsOClib8APCZs0w7KgRf1kHbOIHJeLKv7Qp0l9bhJk4GR7oHwmJWg5cn3IydIaZ5S+MSSE=
    - secure: daWDFrkQ7cbzr69sI5YB2jgPBfz3xAY8fhCqSV0UQJq+toGjWSiKW3H5AaegLigkFVH3mvH9HHcjznLgf92pjQ/LIAbBSKPfzLTZhBMYClv9ofBhNpvMX80qqLG3oIiO0Ua/lYeavs/e9DzpCvpLNBkfhD+EHtI730Cp5lO6b4D1sLRP4shQdmzRWzqFPM3uc5pI4LThjKWF5AudTE6bOE/+HYRhlkRcD7K3/o+RJiq6O2Hg830uVy+JLC5BLHe+tB+vbblsbqhEoPZpZzpMeW7dkwwFtI0QI5GMyJAGqzUn11PAm9wc7NadG2jT7gYpBupy+93RwsqOz+5ehvVdmqNTZNhQnc7cnANlzRl7o8jogTYhvluOkUD4f+hGpekuvLM+sVvYJ6/2C1yCXg6I3Ee6aXUqWv9A9ueS6cRFothesdn9J38Jf7Ak45wVM+ACi1Vw/Z1K3KIoUoiYuMgqRDLVKm4M9zNhWupucgqI3TDNED7zCJ6+PFElNMu925Ok2vt4mgz3tK40A1GozJiNr3ULxycJ91DM3wWw6JHqzwhbYXMn1He1buk5g6ptiqTU4q/gtMnlLPY/5wyH4Bub4rVdIg5lqoz1sdJLwy+TI8jDzgv+q03Nc8gf5HRo29VbClbHTYp3hyZNmH6f9x8Dz9wYIRZQ/05kdkiLWH3xdxU=
    - secure: YgMjbOiA9kKtL6qi56w4oawnMOAUMpTiXT1MMaL7xSQOHdKVdEwb4RIRYJ8y+IStkDzxhYqoozkXDQ1qC9ehEvLI/lPv9j9ULxRlO7T1D6jXyQzXgTQUBro2GmAUuR/5FxMpuQ6EGbH9L5JR3/y4elwmA8RVteNoqqUdQlppl5bbtmcrsyVxfBM9XO4sJKCi+kWj+czQNqfDj9R/U8n/vrGEP5U2bg8SV2Nc9hiNPyexg9z80pvpkgXoTBleMZR718oiXb3/zdwbqTr0qA6sLkO5zBBAR1QTWbaxkVZMEK+YNS/mqtcpT6cSMZ1S/F8q+PSjAf1DoozL7Li1vD5t3HjNIHV3nJNLAl+llkTx1Vk7wjKsQ+e1tQtcSo8/EKPW26OxwIjydDlvpc8AFRgA9ol2Xpun7YrUjPgghVlu6rVqDwCkT5fj7g76tnWk17NNhLdjWrOHe+8qprqM5DVe2XddaQ5B8mQA/PW0I5WcXsiK0Bqktn7zSBIyCl1hx9347sojpV3PN8mXaKv6sTyVBuBO5WwjPO/B0TrUj6XiM05GftFV4NOr9y0mfLyL44n5wXoCFj6r45bJyG6KhUEg7I+RDEjjO55yaRWFtUkd7uX5Mbc66T8iwtBXEZzP8Id2OsKJc7Yt1XVZtcQKMp3SEvCUfi+WvbMjJR7HKTo332U=

cache:
  directories:
    - $API_DIR/node_modules

before_install:
  - openssl aes-256-cbc -K $encrypted_80b785a14e2e_key -iv $encrypted_80b785a14e2e_iv -in $API_DIR/scripts/before_install.sh.enc -out $API_DIR/scripts/before_install.sh -d
  - chmod +x $API_DIR/scripts/before_install.sh
  - $API_DIR/scripts/before_install.sh

script:
  - cd $API_DIR
  - npm install
  - npm test
