branches:
  only:
    - master

language: node_js

node_js:
  - stable

env:
  - API_DIR=server/api

cache:
  directories:
    - $API_DIR/node_modules

before_install:
  - openssl aes-256-cbc -K $encrypted_80b785a14e2e_key -iv $encrypted_80b785a14e2e_iv
    -in server/api/scripts/before_install.sh.enc -out server/api/scripts/before_install.sh -d

script:
  - cd $API_DIR
  - npm install
  - npm test

